#' Extract Key Features from a Data Frame
#'
#' This function takes a data frame and returns a data frame where each row is a
#' developmental stage and the two columns are the gene IDs with the maximum and
#' minimum expression values for that stage.
#'
#' @param df A data frame to extract key features from.
#' @return A data frame where each row is a developmental stage and the two
#' columns are the gene IDs with the maximum and minimum expression values for
#' that stage.
#' @examples
#' # Load the data from a TSV but remove the first 4 lines (comments)
#' data <- readr::read_tsv("./inst/extdata/ERAD_query_results.tsv", skip = 4)
#' # Extract the key features
#' keyFeatures <- extractKeyFeatures(data)
#' @export
#' @importFrom stats which.max
#' @importFrom stats which.min
extractKeyFeatures <- function(df) {
    # Remove non-numeric columns
    numericDf <- df[sapply(df, is.numeric)]

    # Get the gene IDs with max and min expression values for each developmental
    # stage
    maxGenes <- df$`Gene ID`[apply(numericDf, 2, which.max)]
    minGenes <- df$`Gene ID`[apply(numericDf, 2, which.min)]

    # Create a data frame with the gene IDs
    keyFeatures <- data.frame(
        Stage = colnames(numericDf),
        MaxGeneID = maxGenes,
        MinGeneID = minGenes
    )

    # Set the row names to the stages
    rownames(keyFeatures) <- keyFeatures$Stage
    keyFeatures$Stage <- NULL

    # Return the data frame
    return(keyFeatures)
}


#' Provide a snapshot of the data to an LLM to generate a description
#'
#' This function takes a data frame and returns a description of the data
#' generated by an LLM. Only a condensed version of the data is provided to the
#' LLM, to stay within a reasonable context length. The description is generated
#' by the LLM and returned to the user. This can be useful for understanding the
#' general structure of the data.
#'
#' @param df A data frame to describe.
#' @return A description of the data generated by an LLM.
#'
#' @examples
#' # Load the data from a TSV but remove the first 4 lines (comments)
#' data <- readr::read_tsv("./inst/extdata/ERAD_query_results.tsv", skip = 4)
#' # Describe the data
#' description <- describeData(data)
#' @export
describeData <- function(df) {
    # Grab the key features of the data
    keyFeatures <- extractKeyFeatures(df)

    # Define a robust prompt for the LLM to ensure output is consistent and
    # relevant
    prompt <- paste(
        "This data frame contains information about",
        nrow(df),
        "genes. The data frame has",
        ncol(df),
        "columns, which are:\n",
        paste(colnames(df), collapse = ", "),
        "\nBelow are the genes that were found to have the maximum and minimum",
        "expression values for each developmental stage:\n",
        # Add the max and min rows for each developmental stage
        paste(
            paste(
                "(Stage:",
                rownames(keyFeatures),
                "\tMax:",
                keyFeatures$MaxGeneID,
                "\tMin:",
                keyFeatures$MinGeneID,
                ")",
                sep = " "
            ),
            collapse = "\n"
        ),
        "\nThe following is a description of the data frame:",
        sep = " "
    )

    # Send the prompt to the LLM and return the response
    return(getAiResponse(prompt, ""))
}


#' Generate AI Response
#'
#' This function sends a POST request to a local server running an AI model and
#' returns the generated response. The AI model is used to generate a response
#' based on the provided prompt.
#'
#' @param prompt A character string to be used as the prompt for the AI model.
#' @param seed A character string to be used as the seed for the AI model.
#' @return A character string containing the AI model's response.
#' @examples
#' # Generate a response from the AI model
#' response <- getAiResponse("Hello, AI!")
#' @export
#' @importFrom httr POST
#' @importFrom httr content
#' @importFrom httr add_headers
getAiResponse <- function(prompt, seed = "") {
    url <- "http://localhost:11434/api/generate"

    headers <- c(
        "accept" = "application/json",
        "content-type" = "application/json"
    )

    payload <- list(
        "model" = "zephyr",
        "prompt" = prompt,
        "stream" = FALSE,
        "options" = list(
            "temperature" = 0.2,
            "top_k" = 0,
            "top_p" = 0.9
        )
    )

    # If a seed is provided, add it to the payload
    if (seed != "") {
        payload$options$seed <- seed
    }

    response <- httr::POST(url,
        body = payload, httr::add_headers(headers),
        encode = "json"
    )

    return(httr::content(response)$response)
}
